export const FETCH_FILM_LIST_SUCCESS = "FETCH_FILM_LIST";
export const FETCH_FILM_PENDING = "FETCH_FILM_PENDING";
export const FETCH_FILM_LIST_FAIL = "FETCH_FILM_LIST_FAIL";
export const SELECTED_FILM = "SELECTED_FILM";
export const REQUEST_CHARACTERS_SUCCESS = "REQUEST_CHARACTERS_FAIL";
export const REQUEST_CHARACTERS_PENDING = "REQUEST_CHARACTERS_PENDING";
export const REQUEST_CHARACTERS_FAIL = "REQUEST_CHARACTERS_FAIL";
